  development:
    access_key_id: AKIAIQ6FZVBCHSPSSYRA
    secret_code: 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
  production:
    access_key_id: AKIAIQ6FZVBCHSPSSYRA
    secret_code: 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