class SitemapController < ApplicationController
	layout "xmlformat"

	def index
	@sitemap_xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<urlset
      xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\"
      xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
      xsi:schemaLocation=\"http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd\">

<url>
  <loc>http://www.umvox.com/</loc>
</url>
<url>
  <loc>http://www.umvox.com/welcome/howitworks</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/a-humble-request</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/ticketmaster-scam-and-rude-service</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/united-road-services-dangerous-driving-misleading-vehicle-branding</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/verizon-disappointed-before-order-was-even-placed</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/at-t-wireless-sticking-it-to-the-little-guy</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/waggoners-of-death</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/my-sprint-service-is-more-of-a-slow-shuffled-walk</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/selfridges-slogan-the-customer-is-always-right-time-they-start-living-by-that</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/gvtc-and-verizon</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/lufthansa-customer-relations-is-dead</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Advertisement</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Airlines</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Automotive</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Clothes</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Clothing</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Computer%20&amp;%20Internet</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Customer%20Service</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Electronics</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Entertainment</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Florist</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Gaming</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Health%20&amp;%20Fitness</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Home%20&amp;%20Garden</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Mobile%20connection</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Online%20Sales</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Online%20Store</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Other</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Postage</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Services</loc>
</url>
<url>
  <loc>http://www.umvox.com/browse?category=Travel</loc>
</url>
<url>
  <loc>http://www.umvox.com/welcome/howitworks.html</loc>
</url>
<url>
  <loc>http://www.umvox.com/testimonials.html</loc>
</url>
<url>
  <loc>http://www.umvox.com/terms.html</loc>
</url>
<url>
  <loc>http://www.umvox.com/privacy.html</loc>
</url>
<url>
  <loc>http://www.umvox.com/users/password/new</loc>
</url>
<url>
  <loc>http://www.umvox.com/terms</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/singlevox</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/verizon-worry-free-guarantee-not-behind-my-s4</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/travelocity-40-hours-on-phone-100-plus-people-2-weeks-and-still-no-flight-credit-redemption</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/fowler-museum-ucla</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/great-sales-at-kohls</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/terrible-car-salesman</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/south-african-airways-loses-bag-pays-1-5-of-claim</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/american-airlines-poor-service</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/rude-flight-attendants-in-air-china-flight-air-china-ca-987</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/poor-customer-service-runaround-by-travelocity</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/ford-service-department-rip-off</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/vauxhall-vauxnone-more-like</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/les-schwab-tire</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/sears-auto-center-florida-mall-negligence-fraud</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/honda-cr-v-disaster</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/goods-have-still-not-turned-up-from-ann-summers-uk</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/no-clothes</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/victoria-s-secret-giving-me-the-run-around</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/verizon-promised-with-no-intents-in-following-through</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/canon-charges-absurd-shipping-charge</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/internet-still-down-att-totail-fail-horrible-and-unhelpful-customer-service</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/michaelkors-continually-ignoring-emails-and-tweets-about-faulty-watch-strap-asking-for-110-to-fix-it</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/theft-of-domain-name</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/sleepy-s-is-fleecing-us</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/ikea-hell</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/bestbuy-is-not-the-best-buy</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/verizon-no-loyalty</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/yahoo-customer-care-is-neither</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/no-glasses-no-reply-from-sires-crown-again</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/google-is-the-worst</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/jvc-tv-disaster</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/lifeproof-case-destroyed-my-iphone</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/sprint-wont-unlock-my-iphone-5s</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/dropcam-more-like-dropscam</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/google-play-is-never-free</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/waterstones-is-awful</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/b-q-sell-used-products-as-new</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/when-will-you-fix-the-lag-and-major-glitches-in-your-cod-games</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/mattels-rubbish-online-scrabble-game</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/game-took-money-from-me-without-me-knowing</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/1sale-unresponsive</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/odd-future</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/the-geex-no-concept-of-customer-service</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/no-response-to-emails-sent</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/shipping-taking-longer-than-walking</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/amazon-seller</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/subway-manteca-mangers-angel-actually-devil-in-disguise</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/raffle-copter-subscription</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/bravofly-is-simply-the-worst-travel-agency-in-the-history-of-mankind</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/muddy-waters-in-deerfield-beach-fl-overcharges-and-scams-customers</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/problem-with-malfunctioning-lenovo-laptop</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/chase-bank-the-bank-you-should-totally-bank-on</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/around-the-world-with-orbitz</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/6-weeks-waiting-for-a-refund</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/faceon-magazine</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/buytopia</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/comcast-xfinity-home-service</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/amazon-co-delines-reward-points-and-charges-your-gift-card-for-the-order</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/good-for-nothing-clothing-company-really-good-for-nothing</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/the-story-of-a-suspect-cobra-fi2000-tuner-and-a-blown-harley-ecm-or-a-boy-and-his-1000-worth-of-nothin</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/telstra-s-harassing-phone-calls</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/comcastcares-yeah-right</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/baps-shri-swaminarayan-mandir-temple-is-amazing</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/dazz-company-your-smart-carousel-saves-space-but-doesn-t-spin</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/new-google-maps</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/why-can-t-verizon-fix-a-land-line-in-manhattan-for-over-a-year</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/ducati-insurance</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/usps-self-serve-kiosk-takes-money-without-delivering-postage</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/at-t-uverse-reward-cards-rip-off</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/pregnant-can-t-make-receive-calls-not-even-911-with-sprint</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/sire-s-crown-custom-frames-has-the-worst-customer-service</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/vivint-sucks</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/thomson-holidays-thomson-customer-services-and-directors</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/the-amazing-tale-of-lufthansa-s-customer-service</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/supershuttle-loses-my-luggage-their-customer-service-responds-they-are-not-responsible</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/uber-driver-steals-2-500-worth-of-items-uber-does-nothing</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/foursquare-not-helping-with-problem</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/thomson-holidays-tui-will-not-change-my-holiday-dates</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/hyatt-regency-atlanta-cancelled-our-room-in-error-won-t-restore-it</loc>
</url>
<url>
  <loc>http://www.umvox.com/posts/orbitz-glitch-on-website</loc>
</url>
<url>
  <loc>http://www.umvox.com/privacy</loc>
</url>
</urlset>"
	end
end
